import React, { useState, useEffect, useRef } from 'react';
import {
  Card, Box, Typography, ToggleButtonGroup,
  ToggleButton, Divider, GlobalStyles,
} from '@mui/material';
import AutoAwesomeIcon      from '@mui/icons-material/AutoAwesome';
import ConstructionIcon     from '@mui/icons-material/Construction';
import WarningAmberIcon     from '@mui/icons-material/WarningAmber';
import SmartToyOutlinedIcon from '@mui/icons-material/SmartToyOutlined';
import ArticleOutlinedIcon  from '@mui/icons-material/ArticleOutlined';
import { motion, AnimatePresence } from 'framer-motion';

// ─── Brand palette ──────────────────────────────────────────────────────────
const G = {
  blue:   '#4285F4',
  red:    '#EA4335',
  yellow: '#FBBC05',
  green:  '#34A853',
  dark:   '#202124',
  mid:    '#5F6368',
  light:  '#F8F9FA',
  border: 'rgba(0,0,0,0.07)',
  surface: 'rgba(66,133,244,0.04)',
};

// ─── i18n UI strings ────────────────────────────────────────────────────────
const I18N = {
  en: {
    title:         'AI Executive Brief',
    generatedBy:   'Generated by EquiLens AI',
    minRead:       (n) => `${n} min read`,
    worstLabel:    'Worst Affected Group',
    worstSuffix:   'less likely to be approved.',
    fixLabel:      'Recommended Fix',
    complete:      'Analysis complete',
    tags:          ['Bias Analysis', 'Fairness', 'Risk Score', 'Mitigation'],
    noText:        'No explanation generated.',
  },
  hi: {
    title:         'AI कार्यकारी सारांश',
    generatedBy:   'EquiLens AI द्वारा निर्मित',
    minRead:       (n) => `${n} मिनट पढ़ें`,
    worstLabel:    'सर्वाधिक प्रभावित समूह',
    worstSuffix:   'स्वीकृति की संभावना कम।',
    fixLabel:      'अनुशंसित सुधार',
    complete:      'विश्लेषण पूर्ण',
    tags:          ['पक्षपात विश्लेषण', 'निष्पक्षता', 'जोखिम स्कोर', 'समाधान'],
    noText:        'कोई व्याख्या उत्पन्न नहीं हुई।',
  },
  bn: {
    title:         'AI নির্বাহী সারসংক্ষেপ',
    generatedBy:   'EquiLens AI দ্বারা তৈরি',
    minRead:       (n) => `${n} মিনিট পড়ুন`,
    worstLabel:    'সর্বাধিক ক্ষতিগ্রস্ত গোষ্ঠী',
    worstSuffix:   'অনুমোদনের সম্ভাবনা কম।',
    fixLabel:      'প্রস্তাবিত সমাধান',
    complete:      'বিশ্লেষণ সম্পূর্ণ',
    tags:          ['পক্ষপাত বিশ্লেষণ', 'ন্যায্যতা', 'ঝুঁকি স্কোর', 'প্রশমন'],
    noText:        'কোনো ব্যাখ্যা তৈরি হয়নি।',
  },
};

// ─── Shimmer primitive ──────────────────────────────────────────────────────
function Shimmer({ width = '100%', height, borderRadius = 10, sx = {} }) {
  return (
      <Box sx={{
        width, height, borderRadius, flexShrink: 0,
        background: 'linear-gradient(90deg, #f0f2f5 25%, #e4e7eb 50%, #f0f2f5 75%)',
        backgroundSize: '400% 100%',
        animation: 'eb-shimmer 1.6s ease-in-out infinite',
        ...sx,
      }} />
  );
}

// ─── Skeleton ───────────────────────────────────────────────────────────────
function ExplanationSkeleton() {
  return (
      <Box sx={{ p: { xs: 2, sm: 3, md: 4 } }}>
        <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: { xs: 3, sm: 4 }, flexWrap: 'wrap', gap: 2 }}>
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5 }}>
            <Shimmer width={44} height={44} borderRadius={12} />
            <Box>
              <Shimmer width={130} height={18} borderRadius={7} sx={{ mb: 0.8 }} />
              <Shimmer width={90}  height={11} borderRadius={5} />
            </Box>
          </Box>
          <Shimmer width={130} height={36} borderRadius={30} />
        </Box>
        <Shimmer width='100%' height={1} borderRadius={1} sx={{ mb: 3.5, opacity: 0.6 }} />
        <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1.6, mb: 4 }}>
          {[100, 95, 88, 100, 92, 80, 97, 70].map((w, i) => (
              <motion.div key={i} initial={{ opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: i * 0.07, duration: 0.4 }}>
                <Shimmer width={`${w}%`} height={14} borderRadius={6} />
              </motion.div>
          ))}
        </Box>
        <Box sx={{ p: 3, borderRadius: 3, background: `${G.yellow}0a`, border: `1px solid ${G.yellow}30`, display: 'flex', gap: 2, alignItems: 'flex-start', mb: 3 }}>
          <Shimmer width={28} height={28} borderRadius='50%' sx={{ flexShrink: 0 }} />
          <Box sx={{ flex: 1 }}>
            <Shimmer width={140} height={12} borderRadius={5} sx={{ mb: 1.2 }} />
            <Shimmer width='90%' height={12} borderRadius={5} sx={{ mb: 0.8 }} />
            <Shimmer width='70%' height={12} borderRadius={5} />
          </Box>
        </Box>
        <Box sx={{ p: 3, borderRadius: 3, background: `${G.green}0a`, border: `1px solid ${G.green}30`, display: 'flex', gap: 2, alignItems: 'flex-start' }}>
          <Shimmer width={28} height={28} borderRadius='50%' sx={{ flexShrink: 0 }} />
          <Box sx={{ flex: 1 }}>
            <Shimmer width={160} height={12} borderRadius={5} sx={{ mb: 1.2 }} />
            <Shimmer width='85%' height={12} borderRadius={5} sx={{ mb: 0.8 }} />
            <Shimmer width='60%' height={12} borderRadius={5} />
          </Box>
        </Box>
      </Box>
  );
}

// ─── Inline span parser: **bold**, *italic*, `code` ────────────────────────
function parseInline(text) {
  const tokens = text.split(/(\*\*[^*]+\*\*|\*[^*]+\*|`[^`]+`)/g);
  return tokens.map((tok, i) => {
    if (tok.startsWith('**') && tok.endsWith('**'))
      return <Box key={i} component="span" sx={{ fontWeight: 800, color: G.dark }}>{tok.slice(2, -2)}</Box>;
    if (tok.startsWith('*') && tok.endsWith('*'))
      return <Box key={i} component="span" sx={{ fontStyle: 'italic', color: `${G.dark}cc` }}>{tok.slice(1, -1)}</Box>;
    if (tok.startsWith('`') && tok.endsWith('`'))
      return (
          <Box key={i} component="span" sx={{
            fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
            fontSize: '0.85em',
            background: `${G.blue}12`,
            color: G.blue,
            border: `1px solid ${G.blue}25`,
            borderRadius: '5px',
            px: 0.7,
            py: 0.1,
            mx: 0.2,
          }}>{tok.slice(1, -1)}</Box>
      );
    return tok;
  });
}

// ─── Full markdown block renderer ───────────────────────────────────────────
function renderMarkdown(text) {
  if (!text) return null;

  const blocks = [];
  const lines  = text.split('\n');
  let i = 0;
  let numListCounter = 0;

  const bodyTypo = {
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    fontWeight: 500,
    fontSize: { xs: '0.92rem', md: '0.97rem' },
    color: `${G.dark}cc`,
    lineHeight: 1.85,
  };

  while (i < lines.length) {
    const raw  = lines[i];
    const line = raw.trim();

    // blank
    if (!line) {
      blocks.push(<Box key={`gap-${i}`} sx={{ height: '0.55em' }} />);
      numListCounter = 0;
      i++; continue;
    }

    // ── H2: ## Title
    if (/^##\s/.test(line)) {
      const content = line.replace(/^##\s+/, '');
      blocks.push(
          <Box key={`h2-${i}`} sx={{ mt: blocks.length ? 3 : 0, mb: 1.2 }}>
            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5 }}>
              <Box sx={{ width: 3, height: 22, borderRadius: 2, background: `linear-gradient(180deg, ${G.blue}, ${G.red})`, flexShrink: 0 }} />
              <Typography sx={{
                fontFamily: "'Syne', sans-serif",
                fontWeight: 800,
                fontSize: { xs: '0.95rem', sm: '1rem', md: '1.08rem' },
                color: G.dark,
                letterSpacing: '-0.01em',
              }}>
                {parseInline(content)}
              </Typography>
            </Box>
            <Box sx={{ height: 1, background: `linear-gradient(90deg, ${G.blue}30, transparent)`, mt: 1.2 }} />
          </Box>
      );
      numListCounter = 0;
      i++; continue;
    }

    // ── H3: ### Title
    if (/^###\s/.test(line)) {
      const content = line.replace(/^###\s+/, '');
      blocks.push(
          <Typography key={`h3-${i}`} sx={{
            fontFamily: "'Syne', sans-serif",
            fontWeight: 700,
            fontSize: { xs: '0.88rem', sm: '0.92rem', md: '0.98rem' },
            color: G.blue,
            mt: 2, mb: 0.6,
            letterSpacing: '0.01em',
            textTransform: 'uppercase',
          }}>
            {parseInline(content)}
          </Typography>
      );
      numListCounter = 0;
      i++; continue;
    }

    // ── Numbered list: 1. item
    const numMatch = line.match(/^(\d+)\.\s+(.+)/);
    if (numMatch) {
      numListCounter++;
      const num     = numListCounter;
      const content = numMatch[2];
      blocks.push(
          <Box key={`ol-${i}`} sx={{ display: 'flex', gap: 1.5, alignItems: 'flex-start', mb: 0.6, pl: 0.5 }}>
            <Box sx={{
              minWidth: 24, height: 24,
              borderRadius: '50%',
              background: `linear-gradient(135deg, ${G.blue}, #1A73E8)`,
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              flexShrink: 0, mt: '2px',
            }}>
              <Typography sx={{ fontFamily: "'Plus Jakarta Sans'", fontWeight: 800, fontSize: '0.68rem', color: '#fff' }}>
                {num}
              </Typography>
            </Box>
            <Typography sx={{ ...bodyTypo, mb: 0 }}>{parseInline(content)}</Typography>
          </Box>
      );
      i++; continue;
    }

    // ── Bullet list: - or * or •
    if (/^[-•*]\s/.test(line)) {
      numListCounter = 0;
      const content = line.replace(/^[-•*]\s+/, '');
      blocks.push(
          <Box key={`ul-${i}`} sx={{ display: 'flex', gap: 1.5, alignItems: 'flex-start', mb: 0.5, pl: 0.5 }}>
            <Box sx={{
              width: 6, height: 6,
              borderRadius: '50%',
              background: `linear-gradient(135deg, ${G.blue}, ${G.red})`,
              flexShrink: 0, mt: '9px',
            }} />
            <Typography sx={{ ...bodyTypo, mb: 0 }}>{parseInline(content)}</Typography>
          </Box>
      );
      i++; continue;
    }

    // ── Blockquote: > text
    if (/^>\s/.test(line)) {
      numListCounter = 0;
      const content = line.replace(/^>\s+/, '');
      blocks.push(
          <Box key={`bq-${i}`} sx={{
            pl: 2, pr: 1.5, py: 1.2, mb: 1,
            borderLeft: `3px solid ${G.blue}`,
            background: `${G.blue}07`,
            borderRadius: '0 10px 10px 0',
          }}>
            <Typography sx={{ ...bodyTypo, fontStyle: 'italic', color: `${G.dark}99`, mb: 0 }}>
              {parseInline(content)}
            </Typography>
          </Box>
      );
      i++; continue;
    }

    // ── Horizontal rule: --- or ***
    if (/^(-{3,}|\*{3,})$/.test(line)) {
      numListCounter = 0;
      blocks.push(
          <Box key={`hr-${i}`} sx={{ my: 2, height: 1, background: `linear-gradient(90deg, transparent, ${G.border} 20%, ${G.border} 80%, transparent)` }} />
      );
      i++; continue;
    }

    // ── Plain paragraph
    numListCounter = 0;
    blocks.push(
        <Typography key={`p-${i}`} sx={{ ...bodyTypo, mb: 0.5 }}>
          {parseInline(line)}
        </Typography>
    );
    i++;
  }

  return blocks;
}

// ─── Typewriter + markdown renderer ─────────────────────────────────────────
function TypewriterText({ text, speed = 8 }) {
  const [displayed, setDisplayed] = useState('');
  const [done, setDone]           = useState(false);
  const idx = useRef(0);

  useEffect(() => {
    if (!text) return;
    setDisplayed('');
    setDone(false);
    idx.current = 0;

    const id = setInterval(() => {
      idx.current += speed;
      if (idx.current >= text.length) {
        setDisplayed(text);
        setDone(true);
        clearInterval(id);
      } else {
        setDisplayed(text.slice(0, idx.current));
      }
    }, 16);

    return () => clearInterval(id);
  }, [text, speed]);

  return (
      <Box sx={{ position: 'relative' }}>
        {renderMarkdown(displayed)}
        {!done && (
            <Box component="span" sx={{
              display: 'inline-block', width: 2, height: '1.1em',
              background: G.blue, ml: 0.5, verticalAlign: 'middle',
              animation: 'eb-blink 0.75s step-end infinite', borderRadius: 1,
            }} />
        )}
      </Box>
  );
}

// ─── Insight card ────────────────────────────────────────────────────────────
function InsightCard({ color, accentColor, icon: Icon, label, children, delay = 0 }) {
  return (
      <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0 }}
          transition={{ delay, duration: 0.45, ease: [0.22, 1, 0.36, 1] }}
      >
        <Box sx={{
          p: { xs: 2.5, md: 3 }, borderRadius: '16px', mb: 2,
          background: `linear-gradient(135deg, ${color}0e, ${color}05)`,
          border: `1.5px solid ${color}45`,
          display: 'flex', alignItems: 'flex-start', gap: 2,
          position: 'relative', overflow: 'hidden',
          transition: 'box-shadow 0.2s',
          '&:hover': { boxShadow: `0 4px 24px ${color}18` },
        }}>
          <Box sx={{ position: 'absolute', top: -20, right: -20, width: 120, height: 120, background: `radial-gradient(circle, ${color}16, transparent 70%)`, pointerEvents: 'none' }} />
          <Box sx={{
            width: 40, height: 40, borderRadius: '12px',
            background: `${color}1c`,
            display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
          }}>
            <Icon sx={{ color: accentColor, fontSize: 22 }} />
          </Box>
          <Box sx={{ flex: 1, zIndex: 1 }}>
            <Typography sx={{
              fontFamily: "'Plus Jakarta Sans'", fontWeight: 800,
              fontSize: '0.7rem', color: accentColor,
              textTransform: 'uppercase', letterSpacing: '0.12em', mb: 0.8,
            }}>
              {label}
            </Typography>
            {children}
          </Box>
        </Box>
      </motion.div>
  );
}

// ─── Main ExplanationBox ─────────────────────────────────────────────────────
export default function ExplanationBox({ text, worstGroup, worstFactor, suggestedFix, language, onLanguageChange }) {
  const [ready, setReady] = useState(false);
  const lang = language || 'en';
  const t    = I18N[lang] || I18N.en;

  useEffect(() => {
    setReady(false);
    if (!text) return;
    const timer = setTimeout(() => setReady(true), 600);
    return () => clearTimeout(timer);
  }, [text]);

  const handleLangChange = (_, newLang) => {
    if (newLang !== null && onLanguageChange) onLanguageChange(newLang);
  };

  const wordCount = text ? text.split(/\s+/).length : 0;
  const readMins  = Math.max(1, Math.ceil(wordCount / 200));

  return (
      <>
        <GlobalStyles styles={{
          '@keyframes eb-shimmer': {
            '0%':   { backgroundPosition: '-400% 0' },
            '100%': { backgroundPosition:  '400% 0' },
          },
          '@keyframes eb-blink': {
            '0%,100%': { opacity: 1 },
            '50%':     { opacity: 0 },
          },
          '@keyframes eb-flow': {
            '0%':   { backgroundPosition: '0% 50%' },
            '50%':  { backgroundPosition: '100% 50%' },
            '100%': { backgroundPosition: '0% 50%' },
          },
          '@keyframes eb-pulse': {
            '0%':   { transform: 'scale(1)',   opacity: 0.5 },
            '70%':  { transform: 'scale(2.4)', opacity: 0   },
            '100%': { transform: 'scale(1)',   opacity: 0   },
          },
        }} />

        <Box sx={{ position: 'relative', width: '100%' }}>

          {/* Animated aura */}
          <AnimatePresence>
            {ready && (
                <motion.div
                    initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
                    transition={{ duration: 0.8 }}
                    style={{ position: 'absolute', inset: -4, borderRadius: 28, zIndex: 0, pointerEvents: 'none' }}
                >
                  <Box sx={{
                    position: 'absolute', inset: 0, borderRadius: '28px',
                    background: `linear-gradient(135deg, ${G.blue}, ${G.red}, ${G.yellow}, ${G.green}, ${G.blue})`,
                    backgroundSize: '300% 300%',
                    animation: 'eb-flow 8s ease infinite',
                    filter: 'blur(18px)',
                    opacity: 0.18,
                  }} />
                </motion.div>
            )}
          </AnimatePresence>

          <Card sx={{
            position: 'relative', zIndex: 1,
            borderRadius: '24px',
            background: 'rgba(255,255,255,0.92)',
            backdropFilter: 'blur(32px)',
            border: '1px solid rgba(255,255,255,0.95)',
            boxShadow: '0 8px 40px rgba(0,0,0,0.07)',
            overflow: 'hidden',
          }}>
            {/* Rainbow accent bar */}
            <Box sx={{
              height: 4, width: '100%',
              background: `linear-gradient(90deg, ${G.blue} 0%, ${G.red} 33%, ${G.yellow} 66%, ${G.green} 100%)`,
              backgroundSize: '200% 100%',
              animation: 'eb-flow 4s linear infinite',
            }} />

            <AnimatePresence mode="wait">

              {/* Skeleton */}
              {!ready && (
                  <motion.div key="skeleton" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0, transition: { duration: 0.25 } }}>
                    <ExplanationSkeleton />
                  </motion.div>
              )}

              {/* Content */}
              {ready && (
                  <motion.div key="content" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, ease: [0.22, 1, 0.36, 1] }}>
                    <Box sx={{ p: { xs: 2, sm: 3, md: 4 } }}>

                      {/* Header */}
                      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: { xs: 2, sm: 3 }, flexWrap: 'wrap', gap: 2 }}>
                        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5 }}>
                          <motion.div
                              animate={{ rotate: [0, 12, -12, 0], scale: [1, 1.15, 1] }}
                              transition={{ repeat: Infinity, duration: 4, ease: 'easeInOut' }}
                              style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', width: 44, height: 44, borderRadius: 12, background: `${G.blue}18` }}
                          >
                            <AutoAwesomeIcon sx={{ color: G.blue, fontSize: 26 }} />
                          </motion.div>
                          <Box>
                            <Typography sx={{
                              fontFamily: "'Syne', sans-serif",
                              fontWeight: 900,
                              fontSize: { xs: '1rem', sm: '1.15rem', md: '1.25rem' },
                              background: `linear-gradient(135deg, ${G.blue}, #1A73E8)`,
                              WebkitBackgroundClip: 'text',
                              WebkitTextFillColor: 'transparent',
                              letterSpacing: '-0.02em',
                            }}>
                              {t.title}
                            </Typography>
                            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mt: 0.3 }}>
                              <SmartToyOutlinedIcon sx={{ fontSize: 12, color: G.mid }} />
                              <Typography sx={{ fontFamily: "'Plus Jakarta Sans'", fontWeight: 600, fontSize: '0.72rem', color: G.mid }}>
                                {t.generatedBy}
                              </Typography>
                              <Box sx={{ width: 3, height: 3, borderRadius: '50%', background: G.mid, opacity: 0.4 }} />
                              <ArticleOutlinedIcon sx={{ fontSize: 12, color: G.mid }} />
                              <Typography sx={{ fontFamily: "'Plus Jakarta Sans'", fontWeight: 600, fontSize: '0.72rem', color: G.mid }}>
                                {t.minRead(readMins)}
                              </Typography>
                            </Box>
                          </Box>
                        </Box>

                        {/* Language toggle */}
                        <ToggleButtonGroup
                            color="primary"
                            value={lang}
                            exclusive
                            onChange={handleLangChange}
                            size="small"
                            sx={{
                              background: 'rgba(0,0,0,0.03)',
                              borderRadius: '30px',
                              p: 0.5, border: `1px solid ${G.border}`,
                              '& .MuiToggleButton-root': {
                                border: 'none', borderRadius: '30px !important',
                                px: 2.2, py: 0.7, textTransform: 'none',
                                fontWeight: 700, fontSize: '0.8rem',
                                fontFamily: "'Plus Jakarta Sans'",
                                color: 'rgba(0,0,0,0.45)',
                                transition: 'all 0.25s',
                              },
                              '& .Mui-selected': {
                                background: '#fff !important',
                                color: `${G.blue} !important`,
                                boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
                              },
                            }}
                        >
                          <ToggleButton value="en">🇬🇧 EN</ToggleButton>
                          <ToggleButton value="hi">🇮🇳 HI</ToggleButton>
                          <ToggleButton value="bn">🇧🇩 BN</ToggleButton>
                        </ToggleButtonGroup>
                      </Box>

                      <Divider sx={{ mb: 3, borderColor: G.border }} />

                      {/* Body — typewriter with rich markdown */}
                      <Box sx={{ mb: 4, minHeight: 60 }}>
                        <TypewriterText text={text || t.noText} speed={6} />
                      </Box>

                      {/* Insight cards */}
                      <AnimatePresence>
                        {worstGroup && (
                            <InsightCard
                                key="worst"
                                color={G.yellow}
                                accentColor="#D97706"
                                icon={WarningAmberIcon}
                                label={t.worstLabel}
                                delay={0.1}
                            >
                              <Typography sx={{ fontFamily: "'Plus Jakarta Sans'", fontWeight: 600, fontSize: '0.95rem', color: G.dark, lineHeight: 1.65 }}>
                                <Box component="span" sx={{ fontWeight: 900 }}>{worstGroup}</Box>
                                {worstFactor && <> — {worstFactor} {t.worstSuffix}</>}
                              </Typography>
                            </InsightCard>
                        )}

                        {suggestedFix && (
                            <InsightCard
                                key="fix"
                                color={G.green}
                                accentColor="#1E8E3E"
                                icon={ConstructionIcon}
                                label={t.fixLabel}
                                delay={0.2}
                            >
                              <Typography sx={{ fontFamily: "'Plus Jakarta Sans'", fontWeight: 600, fontSize: '0.95rem', color: G.dark, lineHeight: 1.65 }}>
                                {suggestedFix}
                              </Typography>
                            </InsightCard>
                        )}
                      </AnimatePresence>

                      {/* Footer */}
                      <Box sx={{
                        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                        mt: 4, pt: 3, borderTop: `1px solid ${G.border}`, flexWrap: 'wrap', gap: 1.5,
                      }}>
                        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                          <Box sx={{ position: 'relative', width: 10, height: 10 }}>
                            <Box sx={{ position: 'absolute', inset: 0, borderRadius: '50%', background: G.green, animation: 'eb-pulse 1.8s ease-out infinite', opacity: 0.4 }} />
                            <Box sx={{ position: 'absolute', inset: 1, borderRadius: '50%', background: G.green }} />
                          </Box>
                          <Typography sx={{ fontFamily: "'Plus Jakarta Sans'", fontWeight: 600, fontSize: '0.78rem', color: G.mid }}>
                            {t.complete}
                          </Typography>
                        </Box>

                        <Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap' }}>
                          {[G.blue, G.red, G.yellow, G.green].map((c, i) => (
                              <Box key={i} sx={{ px: 1.5, py: 0.5, borderRadius: '50px', background: `${c}12`, border: `1px solid ${c}30` }}>
                                <Typography sx={{ fontFamily: "'Plus Jakarta Sans'", fontWeight: 700, fontSize: '0.7rem', color: c }}>
                                  {t.tags[i]}
                                </Typography>
                              </Box>
                          ))}
                        </Box>
                      </Box>

                    </Box>
                  </motion.div>
              )}
            </AnimatePresence>
          </Card>
        </Box>
      </>
  );
}